# Generated by Django 6.0.4 on 2026-04-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
